#!/bin/sh
set -e
#set -x

PID=$1

if [ -z "$PERF_JAVA_TMP" ]; then
  PERF_JAVA_TMP=/tmp
fi

PERF_COLLAPSE_OPTS="--kernel --tid"
PERF_MAP_OPTIONS="unfoldall"
STACKS=$PERF_JAVA_TMP/out-$PID.stacks
JSTACKS=$PERF_JAVA_TMP/out-$PID.jstacks
COLLAPSED=$PERF_JAVA_TMP/out-$PID.collapsed
COLLAPSED_WITH_THREADS=$PERF_JAVA_TMP/out-threads-$PID.collapsed
PERF_MAP_DIR=$(dirname $(readlink -f $0))/..

if [ ! -x "$FLAMEGRAPH_DIR/stackcollapse-perf.pl" ]; then
  echo "FlameGraph executable not found at '$FLAMEGRAPH_DIR/stackcollapse-perf.pl'. Please set FLAMEGRAPH_DIR to the root of the clone of https://github.com/brendangregg/FlameGraph."
  exit
fi

#if [ ! -x jstack ]; then
#  echo "Cannot find jstack executable on the path. Please add JDK_HOME/bin to your path."
#  exit
#fi

if [ -z "$PERF_DATA_FILE" ]; then
  PERF_DATA_FILE=$PERF_JAVA_TMP/perf-$PID.data
fi

if [ -z "$PERF_FLAME_OUTPUT" ]; then
  PERF_FLAME_OUTPUT=flamegraph-$PID.svg
fi

if [ -z "$PERF_FLAME_OPTS" ]; then
    PERF_FLAME_OPTS="--color=java"
fi

jstack $1 > $JSTACKS
$PERF_MAP_DIR/bin/perf-java-record-stack $*
sudo perf script -i $PERF_DATA_FILE > $STACKS
$FLAMEGRAPH_DIR/stackcollapse-perf.pl $PERF_COLLAPSE_OPTS $STACKS > $COLLAPSED
$PERF_MAP_DIR/bin/convert_thread_names.py $JSTACKS $COLLAPSED $COLLAPSED_WITH_THREADS
cat $COLLAPSED_WITH_THREADS | $FLAMEGRAPH_DIR/flamegraph.pl $PERF_FLAME_OPTS > $PERF_FLAME_OUTPUT
echo "Flame graph SVG written to PERF_FLAME_OUTPUT='`readlink -f $PERF_FLAME_OUTPUT`'."
